package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Confederacion generated by hbm2java
 */
@Entity
@Table(name = "Confederacion", catalog = "FutbolDB_V2", uniqueConstraints = @UniqueConstraint(columnNames = "nombre") )
public class Confederacion implements java.io.Serializable {

	private Integer idConfederacion;
	private String nombre;
	private Integer cantidadDePaises;
	//private Set<Pais> paises = new HashSet<Pais>(0);

	public Confederacion() {
	}

	public Confederacion(String nombre) {
		this.nombre = nombre;
	}

	public Confederacion(String nombre, Integer cantidadDePaises/*, Set<Pais> paises*/) {
		this.nombre = nombre;
		this.cantidadDePaises = cantidadDePaises;
		//this.paises = paises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idConfederacion", unique = true, nullable = false)
	public Integer getIdConfederacion() {
		return this.idConfederacion;
	}

	public void setIdConfederacion(Integer idConfederacion) {
		this.idConfederacion = idConfederacion;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cantidadDePaises")
	public Integer getCantidadDePaises() {
		return this.cantidadDePaises;
	}

	public void setCantidadDePaises(Integer cantidadDePaises) {
		this.cantidadDePaises = cantidadDePaises;
	}

	@Override
	public String toString() {
		return " {\"idConfederacion\":\"" + idConfederacion + "\",\"nombre\":\"" + nombre + "\",\"cantidadDePaises\":\""
				+ cantidadDePaises + "\"}";
	}



	

	
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "confederacion")
	public Set<Pais> getPaises() {
		return this.paises;
	}

	public void setPaises(Set<Pais> paises) {
		this.paises = paises;
	}*/

}
