package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.ObjectIdGenerator;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.google.common.base.Objects;

/**
 * Confederacion generated by hbm2java
 */
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="_idConfederacion", scope=Confederacion.class)
@Entity
@Table(name = "Confederacion", catalog = "FutbolDB_V2", uniqueConstraints = @UniqueConstraint(columnNames = "nombre") )
//@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"/*"paises"*/})
public class Confederacion implements java.io.Serializable {

	/**
	 * 
	 */
	@JsonIgnore
	private static final long serialVersionUID = 2854333559368929418L;
	private Integer idConfederacion;
	private String nombre;
	private Integer cantidadDePaises;
	//@JsonBackReference(value="confederacionPais")
	private Set<Pais> paises = new HashSet<Pais>(0);

	public Confederacion() {
	}

	public Confederacion(Integer idConfederacion, String nombre, Integer cantidadDePaises, Set<Pais> paises) {
		super();
		this.idConfederacion = idConfederacion;
		this.nombre = nombre;
		this.cantidadDePaises = cantidadDePaises;
		this.paises = paises;
	}

	public Confederacion(String nombre) {
		this.nombre = nombre;
	}

	public Confederacion(String nombre, Integer cantidadDePaises, Set<Pais> paises) {
		this.nombre = nombre;
		this.cantidadDePaises = cantidadDePaises;
		this.paises = paises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idConfederacion", unique = true, nullable = false)
	public Integer getIdConfederacion() {
		return this.idConfederacion;
	}

	public void setIdConfederacion(Integer idConfederacion) {
		this.idConfederacion = idConfederacion;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cantidadDePaises")
	public Integer getCantidadDePaises() {
		return this.cantidadDePaises;
	}

	public void setCantidadDePaises(Integer cantidadDePaises) {
		this.cantidadDePaises = cantidadDePaises;
	}
	
	/*@Override
	public String toString() {
		return "{\"idConfederacion\":" + idConfederacion + ",\"nombre\":\"" + nombre + "\",\"cantidadDePaises\":"
				+ cantidadDePaises + "\"paises\":" + paises + "}";
	}*/
	@Override
	public String toString() {
		return "{\"idConfederacion\":" + idConfederacion + ",\"nombre\":\"" + nombre + "\",\"cantidadDePaises\":"
				+ cantidadDePaises + "}";
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "confederacion")
	public Set<Pais> getPaises() {
		return this.paises;
	}

	public void setPaises(Set<Pais> paises) {
		this.paises = paises;
	}
	
	@Override
	public int hashCode() {
		return Objects.hashCode(getNombre(), getCantidadDePaises(), getPaises());
	}

	@Override
	public boolean equals(Object object) {
		if(object instanceof Confederacion) {
			Confederacion other = (Confederacion)object;
			return Objects.equal(getNombre(), other.getNombre())
					&& Objects.equal(getCantidadDePaises(), other.getCantidadDePaises())
					&& Objects.equal(getPaises(), other.getPaises());
		}
		else
			return false;
	}
	
}
