package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Estadio generated by hbm2java
 */
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="_idEstadio", scope=Estadio.class)
@Entity
@Table(name = "Estadio", catalog = "FutbolDB_V2")
//@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Estadio implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4935744021736402736L;
	private Integer idEstadio;
	private String nombre;
	private Integer capacidad;
	//@JsonBackReference(value="equipoEstadio")
	private Set<Equipo> equipos = new HashSet<Equipo>(0);

	public Estadio() {}

	public Estadio(String nombre, Integer capacidad, Set<Equipo> equipos) {
		this.nombre = nombre;
		this.capacidad = capacidad;
		this.equipos = equipos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstadio", unique = true, nullable = false)
	public Integer getIdEstadio() {
		return this.idEstadio;
	}

	public void setIdEstadio(Integer idEstadio) {
		this.idEstadio = idEstadio;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "capacidad")
	public Integer getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(Integer capacidad) {
		this.capacidad = capacidad;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "estadios")
	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

	@Override
	public String toString() {
		return " {\"idEstadio\":" + idEstadio + ",\"nombre\":\"" + nombre + "\",\"capacidad\":" + capacidad
				+ "}";
	}

	
	
}
