package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name = "Jugador", catalog = "FutbolDB_V2", uniqueConstraints = @UniqueConstraint(columnNames = "cedula") )
public class Jugador implements java.io.Serializable {

	private Integer idJugador;
	private Equipo equipo;
	private Pais pais;
	private Patrocinador patrocinador;
	private int cedula;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private double salario;
	private int anhosContratoRestante;
	private Date fechaNacimiento;
	private String posicion;
	private Integer edad;

	public Jugador() {
	}

	public Jugador(Pais pais, int cedula, String nombre, String apellido1, String apellido2, double salario,
			int anhosContratoRestante, Date fechaNacimiento, String posicion) {
		this.pais = pais;
		this.cedula = cedula;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.salario = salario;
		this.anhosContratoRestante = anhosContratoRestante;
		this.fechaNacimiento = fechaNacimiento;
		this.posicion = posicion;
	}

	public Jugador(Equipo equipo, Pais pais, Patrocinador patrocinador, int cedula, String nombre, String apellido1,
			String apellido2, double salario, int anhosContratoRestante, Date fechaNacimiento, String posicion,
			Integer edad) {
		this.equipo = equipo;
		this.pais = pais;
		this.patrocinador = patrocinador;
		this.cedula = cedula;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.salario = salario;
		this.anhosContratoRestante = anhosContratoRestante;
		this.fechaNacimiento = fechaNacimiento;
		this.posicion = posicion;
		this.edad = edad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idJugador", unique = true, nullable = false)
	public Integer getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(Integer idJugador) {
		this.idJugador = idJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEquipo")
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPatrocinador")
	public Patrocinador getPatrocinador() {
		return this.patrocinador;
	}

	public void setPatrocinador(Patrocinador patrocinador) {
		this.patrocinador = patrocinador;
	}

	@Column(name = "cedula", unique = true, nullable = false)
	public int getCedula() {
		return this.cedula;
	}

	public void setCedula(int cedula) {
		this.cedula = cedula;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false, length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", nullable = false, length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "salario", nullable = false, precision = 22, scale = 0)
	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

	@Column(name = "anhosContratoRestante", nullable = false)
	public int getAnhosContratoRestante() {
		return this.anhosContratoRestante;
	}

	public void setAnhosContratoRestante(int anhosContratoRestante) {
		this.anhosContratoRestante = anhosContratoRestante;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "posicion", nullable = false, length = 45)
	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

}
