package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "Pais", catalog = "FutbolDB_V2", uniqueConstraints = { @UniqueConstraint(columnNames = "nombre"),
		@UniqueConstraint(columnNames = "puestoRankingFifa") })
public class Pais implements java.io.Serializable {

	private Integer idPais;
	private Confederacion confederacion;
	private String nombre;
	private int puestoRankingFifa;
	private Set<Equipo> equipos = new HashSet<Equipo>(0);
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);

	public Pais() {
	}

	public Pais(Confederacion confederacion, String nombre, int puestoRankingFifa) {
		this.confederacion = confederacion;
		this.nombre = nombre;
		this.puestoRankingFifa = puestoRankingFifa;
	}

	public Pais(Confederacion confederacion, String nombre, int puestoRankingFifa, Set<Equipo> equipos,
			Set<Jugador> jugadors) {
		this.confederacion = confederacion;
		this.nombre = nombre;
		this.puestoRankingFifa = puestoRankingFifa;
		this.equipos = equipos;
		this.jugadors = jugadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPais", unique = true, nullable = false)
	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idConfederacion", nullable = false)
	public Confederacion getConfederacion() {
		return this.confederacion;
	}

	public void setConfederacion(Confederacion confederacion) {
		this.confederacion = confederacion;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "puestoRankingFifa", unique = true, nullable = false)
	public int getPuestoRankingFifa() {
		return this.puestoRankingFifa;
	}

	public void setPuestoRankingFifa(int puestoRankingFifa) {
		this.puestoRankingFifa = puestoRankingFifa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

}
