package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patrocinador generated by hbm2java
 */
@Entity
@Table(name = "Patrocinador", catalog = "FutbolDB_V2")
public class Patrocinador implements java.io.Serializable {

	private Integer idPatrocinador;
	private String nombre;
	private Set<Equipo> equipos = new HashSet<Equipo>(0);
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);

	public Patrocinador() {
	}

	public Patrocinador(String nombre) {
		this.nombre = nombre;
	}

	public Patrocinador(String nombre, Set<Equipo> equipos, Set<Jugador> jugadors) {
		this.nombre = nombre;
		this.equipos = equipos;
		this.jugadors = jugadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPatrocinador", unique = true, nullable = false)
	public Integer getIdPatrocinador() {
		return this.idPatrocinador;
	}

	public void setIdPatrocinador(Integer idPatrocinador) {
		this.idPatrocinador = idPatrocinador;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "patrocinadors")
	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patrocinador")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

}
