package com.jordanec.restbootexample.model;
// Generated 04-ene-2016 19:14:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.base.Objects;
import com.jordanec.restbootexample.util.TeamJsonSerializer;
import com.jordanec.restbootexample.util.TeamJsonDeserializer;

/**
 * Team generated by hbm2java
 */
@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="idTeam", scope=Team.class)
@Entity
@Table(name = "Team", catalog = "FutbolDB_V3")
//@JsonIgnoreProperties({"sponsors", "stadiums", "players", "country"})	
//@JsonSerialize(using=TeamJsonSerializer.class)
//@JsonDeserialize(using=TeamJsonDeserializer.class)
public class Team implements java.io.Serializable {
	/**
	 * 
	 */
	//@JsonIgnore
	private static final long serialVersionUID = -8766290831934018801L;
	private Integer idTeam;
	//@JsonManagedReference(value="countryTeam")
	private Country country;
	private String name;
	private int championships;
	//@JsonManagedReference(value="teamSponsor")
	private Set<Sponsor> sponsors = new HashSet<Sponsor>(0);
	//@JsonManagedReference(value="teamStadium")
	private Set<Stadium> stadiums = new HashSet<Stadium>(0);
	//@JsonBackReference(value="teamPlayer")
	private Set<Player> players = new HashSet<Player>(0);

	public Team() {}

	public Team(Country country, String name, int championships) {
		this.country = country;
		this.name = name;
		this.championships = championships;
	}

	public Team(Integer idTeam, Country country, String name, int championships, Set<Sponsor> sponsors,
			Set<Stadium> stadiums, Set<Player> players) {
		super();
		this.idTeam = idTeam;
		this.country = country;
		this.name = name;
		this.championships = championships;
		this.sponsors = sponsors;
		this.stadiums = stadiums;
		this.players = players;
	}

	public Team(Country country, String name, int championships, Set<Sponsor> sponsors, Set<Stadium> stadiums,
			Set<Player> players) {
		this.country = country;
		this.name = name;
		this.championships = championships;
		this.sponsors = sponsors;
		this.stadiums = stadiums;
		this.players = players;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTeam", unique = true, nullable = false)
	public Integer getIdTeam() {
		return this.idTeam;
	}

	public void setIdTeam(Integer idTeam) {
		this.idTeam = idTeam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCountry", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "championships", nullable = false)
	public int getChampionships() {
		return this.championships;
	}

	public void setChampionships(int championships) {
		this.championships = championships;
	}

	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Team_Sponsor", catalog = "FutbolDB_V3", joinColumns = {
			@JoinColumn(name = "idTeam", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idSponsor", nullable = false, updatable = false) })
	public Set<Sponsor> getSponsors() {
		return this.sponsors;
	}

	public void setSponsors(Set<Sponsor> sponsors) {
		this.sponsors = sponsors;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Team_Stadium", catalog = "FutbolDB_V3", joinColumns = {
			@JoinColumn(name = "idTeam", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idStadium", nullable = false, updatable = false) })
	public Set<Stadium> getStadiums() {
		return this.stadiums;
	}

	public void setStadiums(Set<Stadium> stadiums) {
		this.stadiums = stadiums;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "team")
	public Set<Player> getPlayers() {
		return this.players;
	}

	public void setPlayers(Set<Player> players) {
		this.players = players;
	}
	/*
	@Override
	public int hashCode() {
		return Objects.hashCode(getName(), getChampionships(), getStadiums(), getPlayers(),
				getCountry(), getSponsors());
	}

	@Override
	public boolean equals(Object object) {
		if(object instanceof Team) {
			Team other = (Team)object;
			return Objects.equal(getName(), other.getName())
				&& Objects.equal(getChampionships(), other.getChampionships())
				&& Objects.equal(getStadiums(), other.getStadiums())
				&& Objects.equal(getPlayers(), other.getPlayers())
				&& Objects.equal(getCountry(), other.getCountry())
				&& Objects.equal(getSponsors(), other.getSponsors());
		}
		else
			return false;
	}*/

	/*@Override
	public String toString() {
		return " {\"idTeam\":" + idTeam + ",\"country\":\"" + country + "\",\"name\":\"" + name
				+ "\",\"championships\":" + championships + "}";
	}*/
	
	@Override
	public String toString() {
		return " {\"idTeam\":\"" + idTeam + "\",\"country\":\"" + country + "\",\"name\":\"" + name
				+ "\",\"championships\":\"" + championships + "\",\"sponsors\":\"" + sponsors
				+ "\",\"stadiums\":\"" + stadiums + "\",\"players\":\"" + players + "\"}";
	}
	
	
}
